### ISSUE TITLE
[FEATURE] Add People Involved

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#105]
**Is your feature request related to a problem? Please describe.**
Add People Involved

- [x] Create
- [x] Read
- [x] Update
- [x] Delete

Each People will have the attributes:
- Id
- Name
- Total_people
- Vehicle
- Phone
- People

The view has to look like this:
![Recerca - Actuants – People involved - View](https://user-images.githubusercontent.com/26260104/95002221-d84a8c00-05d1-11eb-9078-fa1834a0c436.png)

On Add button it appears a modal:
![Recerca - Actuants – People involved - Add](https://user-images.githubusercontent.com/26260104/95002226-dc76a980-05d1-11eb-9fc1-c62dca9c0897.png)

On Edit in the action button it appears a modal:
![Recerca - Actuants – People involved - Edit](https://user-images.githubusercontent.com/26260104/95002227-e0a2c700-05d1-11eb-9cf3-7aac49a0643c.png)

**Comment by mo2l** [comment]
Hey I am Marcel a passionate Laravel developer and member of a local civil protection unit. If you are open to new contributors I would be happy to help you out.

I am a voluntary member for the last eleven years seeing different aspects of this work. (on-site, organisation and leading)

Beside working on issues marked as "help wanted" I could help with translating the app into German, as this is my native language. 

Hope to hear from you

If you have any questions feel free to ask right away :)

Best regards

Marcel

**Comment by eduayme** [comment]
Hi Marcel,

Amazing news! For sure, you are more than welcome as a contributor.

Translating the app into German is not a priority but if you open a new issue and create the translation will be used for sure. For any question about the project don't hesitate to contact me.

Best regards :D

**Comment by mo2l** [comment]
@eduayme thanks for the warm welcoming :)

Will take on some open issues for the moment and when there those are done and I find some more time I will start translating it :)

**Comment by JoseDeFreitas** [comment]
Hello! I don't know if there's a Spanish translation 🤔. If there isn't, I would like to do it!
Apart from that, for this repository to be eligible to participate in the Hacktoberfest event it should have the "hacktoberfest" topic.

**Comment by eduayme** [comment]
Hi @JoseDeFreitas. Yes, a Spanish translation already exists.
Thanks for the tip. I will add the "hacktoberfest" topic right now.

**Comment by mo2l** [comment]
starting to work on this issue :)

**Comment by mo2l** [comment]
@eduayme do you want the action buttons to have the same restrictions as the ones from searches -> incidents?

**Comment by eduayme** [comment]
@mo2l Yes, exactly. All action buttons have to follow the same logic

**Comment by mo2l** [comment]
@eduayme just curious as I can't see a action to open the read route, do we really need it when there is no see the specific data of one involved_people entry?

The action is prepared and I added an empty view, in case we need it but we could get rid of that if there is no need for it yet.

**Comment by eduayme** [comment]
@mo2l what do you mean when you say "read route". If there si no data the tab view should have an illustration related to involved_people, a sentence saying there is no involved people registered and a button to add a person. I take the illustration from [undrow.co](https://undraw.co/illustrations)with principal color #BF0712. The final result with empty data should be similar to the one already implemented in the searches and practices when empty data:
<img width="1440" alt="Screenshot 2020-10-09 at 14 54 30" src="https://user-images.githubusercontent.com/26260104/95585345-634adc80-0a3f-11eb-9e51-2d54b74bbdcc.png">
