### ISSUE TITLE
[FEATURE] Add Groups

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#106]
**Is your feature request related to a problem? Please describe.**
Add Groups

- [ ] Create
- [ ] Read
- [ ] Update
- [ ] Delete

Each Group will have the attributes:
- Id
- Status (Active or Closed)
- Vehicle
- Broadcast
- GPS
- People involved

The view has to look like this:
![Recerca - Actuants – Groups - View](https://user-images.githubusercontent.com/26260104/95001504-e34dee00-05ca-11eb-8415-1d813368e67a.png)

On Add button it appears a modal:
![Recerca - Actuants – Groups - Add](https://user-images.githubusercontent.com/26260104/95001579-8bfc4d80-05cb-11eb-8251-f2e4aa43a456.png)

On Edit in the action button it appears a modal:
![Recerca - Actuants – Groups - Edit](https://user-images.githubusercontent.com/26260104/95001581-90c10180-05cb-11eb-8012-b41fed30adfe.png)

**Comment by jovynode** [comment]
@eduayme , I'll work on this, you may assign to me. Cheers 👍

**Comment by jovynode** [comment]
PR #181 sent !
