### ISSUE TITLE
[FEATURE] Add Leaders

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#107]
**Is your feature request related to a problem? Please describe.**
Add Leaders

- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by nishanb** [comment]
@eduayme can i take this ?

**Comment by eduayme** [comment]
@nishanb for sure

**Comment by eduayme** [comment]
Each leader will have the attributes:
- Id
- Phone number
- Name
- Start
- End

The view has to look like this:
![leaders](https://user-images.githubusercontent.com/26260104/95000435-1d19f700-05c1-11eb-91af-dc96b69488b8.png)

On Edit in the action button it appears a modal:
![leaders-edit](https://user-images.githubusercontent.com/26260104/95000480-869a0580-05c1-11eb-8ad9-fef99da2f01f.png)

**Comment by nishanb** [comment]
- [ ] Create [WIP]
- [ ] Read
- [ ]  Update
- [ ]  Delete
