### ISSUE TITLE
[FEATURE] Add Tasks

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#108]
**Is your feature request related to a problem? Please describe.**
Add Tasks

- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by AleksandarMitevski** [comment]
Hello, i'd like to try to solve this issue.

**Comment by eduayme** [comment]
It needs to be another table like all content in the other tabs.
The class "Task" have this parameters:

- Sector (string)
- Status (string | "to_do", "in_progress", "done" options | default "to_do")
- Group (integer)
- Start (datetime)
- End (datetime)
- Type (string)
- Description (longText)
- Gpx (integer | 1 or 0 | default 0)

Here you have the design:
- Index:
![Recerca - Tasques](https://user-images.githubusercontent.com/26260104/93020821-b87e0480-f5df-11ea-863d-f2c02fa2973e.png)

- Description popup:
![Recerca - Tasques – 1](https://user-images.githubusercontent.com/26260104/93020831-c2a00300-f5df-11ea-8d73-d5263c00fac3.png)

- Edit popup:
![Recerca - Tasques – Afegir](https://user-images.githubusercontent.com/26260104/93020841-ca5fa780-f5df-11ea-9e79-f18751f83f0c.png)

**Comment by AleksandarMitevski** [comment]
Alright thank you.

**Comment by AleksandarMitevski** [comment]
Hello @eduayme ,

I have a couple of questions regarding this task.

What kind of input does the dispositiu rastreig/tracking device expect and to what table does it need to be persisted into or is it something not yet developed ?

Also should i create the create task view or just the given designs ?

**Comment by AleksandarMitevski** [comment]
Dispositiu  rastreig is something related to the resources tab ?

**Comment by eduayme** [comment]
> Hello @eduayme ,
> 
> I have a couple of questions regarding this task.
> 
> What kind of input does the dispositiu rastreig/tracking device expect and to what table does it need to be persisted into or is it related to something not yet developed in the resources tab ?
> 
> Also should i create the create task view or just the given designs ?

- The tracking device (dispositiu restreig) is a gpx file with a string name. It is optional to add it on each task. If a task has a gpx file in the table the column "GPX" will be green, otherwise will be red.

- The view should be in the "task" tab inside the existing search view that currently has a mockup image. The view need to have a create task bottom on the top right as all other table list views and the table displaying all tasks as the next image:
![93020821-b87e0480-f5df-11ea-863d-f2c02fa2973e](https://user-images.githubusercontent.com/26260104/93670186-b44b5e80-fa99-11ea-91f5-0c3f505c89f3.png)

**Comment by AleksandarMitevski** [comment]
Thank you for the reply @eduayme .

I already created the tasks table going off the screenshot you provided in your first reply, I only need to change the color scheme if it's important.

![tasks2](https://user-images.githubusercontent.com/59975218/93671606-9e8f6680-faa4-11ea-9629-e144682b4cb3.PNG)

I was asking if i should create a view for Task Creation like the create.blade.php for Incidents since you didn't include a design for that kind of view.

**Comment by eduayme** [comment]
@AleksandarMitevski That looks awesome!

Yes, the view should be in /resources/views/searches/tasks and inside there "index.blade.php" for this table and "edit.blade.php" for the editing modal.
