### ISSUE TITLE
[FEATURE] Refactor margin and padding

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#123]
**Describe the solution you'd like**
 Refactor margin and padding with bootstrap classes

**Comment by jovynode** [comment]
@eduayme, I can work on this for hacktoberfest. Do you want something like this --> https://getbootstrap.com/docs/4.0/utilities/spacing/#notation
Or, just remove those existing inline style attributes then add bootstrap classes.

**Comment by eduayme** [comment]
@jovynode nop, I already solved this. Sorry I didn't remember to close this issue

**Comment by jovynode** [comment]
@eduayme no worries.  I saw your commit just after I sent my message. Let me know if you need further help. 👍

**Comment by eduayme** [comment]
@jovynode yep, I just checked and finished fixing some small things. Main refactor were done in other issue some weeks ago. Now the only things left is this 2 issues: #107 and #105 (this last one with a PR reviewed and waiting for changes). If you want to work on something would be #107 as @nishanb looks like is not advancing further with the issue.

**Comment by jovynode** [comment]
@eduayme , sorry, i saw your last message just today. You can assign #107 to me. I can send the PR soon.
