### ISSUE TITLE
[BUG] Fix LaRecipe docs

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#182]
**Describe the bug**
In /docs the LaRecipe package is not working. Is displaying nothings

**To Reproduce**
1. Go to the footer
2. Click on 'Documentation'
3. See error

**Expected behavior**
A docs page should be displayed here

**Screenshots**
<img width="1440" alt="Screenshot 2020-10-12 at 15 14 06" src="https://user-images.githubusercontent.com/26260104/95750573-a30eff80-0c9d-11eb-82ab-39acab504b81.png">

**Comment by jovynode** [comment]
I'll take this one, please assign to me. ;)
