### ISSUE TITLE
[FEATURE] Create Docker image

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#194]
**Describe the solution you'd like**
Create a Docker image to automatically launch the app and DB

**Comment by jonadoe** [comment]
Hi Eduard. If you like I can take care of this issue. 
I would do this using a docker compose configuration. 
Do you have any specific requirements for the setup?

**Comment by eduayme** [comment]
Not really. I am open to any suggestion.

**Comment by jonadoe** [comment]
Ok, I will create a PR with a proposal

**Comment by jonadoe** [comment]
Hi @eduayme 
any questions regarding the docker code or anything which needs improvement?

**Comment by eduayme** [comment]
Hi @jonadoe
Not really, everything looks fine and it works well so perfect!
Thanks :)
