### ISSUE TITLE
[FEATURE] Redesign UX/UI

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#209]
Redesign the User Experience and User Interface.

- [ ] Remove 2 levels of tabs
- [ ] Improve responsive
- [ ] Same main navbar all the time

**Comment by MuhammadUmair98** [comment]
Hey i am a beginner but i would love to contribute what i can to this one :).

**Comment by eduayme** [comment]
@MuhammadUmair98 sure

**Comment by theshendeveloper** [comment]
Hey
Can I contribute something to the project?

**Comment by iamRabia-N** [comment]
Hi! I want to contribute in redesigning User Experience and User Interface of "RescueApp" website. So, if you are looking for enhancement in design of website, do let me know. I would appreciate the opportunity to contribute in it.
