### ISSUE TITLE
[FEATURE] Admin dashboard

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#210]
Create a dashboard view to control all data from their searches and users.

**Comment by bsimser** [comment]
Are there any specs/examples/ideas for this?

**Comment by eduayme** [comment]
I did this mockup and it would be something similar. Only for admin users like the users manager index.
![dashboard-admin](https://user-images.githubusercontent.com/26260104/112962029-3c47aa80-9146-11eb-86e9-6fcb82b8f946.png)

**Comment by bsimser** [comment]
Looks good, I'd like to take this task on please.

**Comment by bhimbho** [comment]
i see alot of heavy code lying around in the controllers. I like to contribute by refactoring

**Comment by eduayme** [comment]
All refactor, if it is really helpful, is more than welcome @bhimbho

**Comment by Adams-Ijachi** [comment]
Hello i am new to contributing and would love to know how i can help

**Comment by PatrickMamsery** [comment]
Hello @eduayme I am relatively new to open-source contributions, and I would very much appreciate the chance to help out. Thank you.

**Comment by danielh-official** [comment]
If possible, can we use a built-in solution like [Orchid](https://orchid.software/en/)?
