### ISSUE TITLE
Improving the content of the description.md file

### ISSUE THREAD

**Issue by OguzieVictor** [eduayme/RescueApp#276]
I'm not satisfied with the description given in the English version of the description.md file.

The description needs to be grammatically accurate while elaborating the benefits the app offers.

**Comment by Shalini469717** [comment]
I would like to work on this issue. Could you please assign this to me?

**Comment by Shalini469717** [comment]
#277

**Comment by eduayme** [comment]
@Shalini469717 feel free to review it again and fix the merge conflicts to be able to merge it
