### ISSUE TITLE
Improving the English Version of installation.md and objectives.md for better clarity and readability

### ISSUE THREAD

**Issue by patchh** [eduayme/RescueApp#298]
I believe the English version of the files installation.md and objectives.md can be updated for better readability and clarity. Some installation steps use numbered options when only one option is available and there is a typo located in the installation.md file. The majority of the objectives listed in the objectives.md file all begin with "To create", I believe this can be improved to reduce repetitive wording. Some of the grammar for this file could also be improved.

**Comment by eduayme** [comment]
Sure @patchh! You are more than welcome to open a PR
