### ISSUE TITLE
[FEATURE] Add admin page with all logs from users

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#46]
**Is your feature request related to a problem? Please describe.**
As a admin user I can not see what users do.

**Describe the solution you'd like**
I would love to have an admin page that allows me to see activity logs from all users.

**Describe alternatives you've considered**
- Integrate [laravel-logger](https://github.com/jeremykenedy/laravel-logger).

**Additional context**

- List activity: 
![68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f6769746875622d70726f6a6563742d696d616765732f6c61726176656c2d6c6f676765722f312d64617368626f6172642e6a7067](https://user-images.githubusercontent.com/26260104/67610455-461bf000-f793-11e9-81e5-545c2ac3b475.jpeg)
[Image source](https://github.com/jeremykenedy/laravel-logger) from laravel-logger project

**Comment by Dhavalc2012** [comment]
Can you assign this task to me? I shall work on figuring out this feature implementation.

**Comment by Dhavalc2012** [comment]
I have completed with the backend generation of logs, for the routes do we have defined gates or policies to distinguish between users, guest and admin to view pages?

**Comment by eduayme** [comment]
The logs should only be visible to admin users. The backend, before sending any info, should check the profile and see if it is an admin.

**Comment by Dhavalc2012** [comment]
Oh alright. I shall create the logic for admin-only access which can be used by other pages as well. :+1:
