### ISSUE TITLE
[FEATURE] Add incidents in a rescue

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#49]
**Is your feature request related to a problem? Please describe.**
Users should be able to add incidents when the rescue is in progress

**Describe the solution you'd like**
A new tab inside a rescue (as Data and Closing) to list and CRUD incidents.
- [x] Add an incident.
- [x] Edit an incident.
- [x] Delete an incident.
- [x] Add images.
- [x] Display images in a popup gallery.

**Additional context**
Should look like this:
![Recerca - Incidencies](https://user-images.githubusercontent.com/26260104/68533597-75e5fe80-0322-11ea-93fc-238155e7b266.png)
![Recerca - Incidencies – Crear Incidencia](https://user-images.githubusercontent.com/26260104/68533592-754d6800-0322-11ea-9258-5a09dddc4623.png)
![Recerca - Incidencies – Editar Incidencia](https://user-images.githubusercontent.com/26260104/68533594-754d6800-0322-11ea-8225-9a0b1fdcde1f.png)
![Recerca - Incidencies – Foto 1](https://user-images.githubusercontent.com/26260104/68533595-754d6800-0322-11ea-9346-9e182109bb87.png)
![Recerca - Incidencies – Foto 2](https://user-images.githubusercontent.com/26260104/68533596-75e5fe80-0322-11ea-98b0-69927b355180.png)

**Comment by mobeendev** [comment]
@eduayme can I take this one.

**Comment by mobeendev** [comment]
@eduayme I am unable to hit the login route and I am on Apache.
is there any particular config that I should to get in there!!.
Thanks in advance.

**Comment by eduayme** [comment]
@mobeendev sure, you can take it. All the info is in the [Wiki](https://github.com/eduayme/RescueApp/wiki)

**Comment by mobeendev** [comment]
> @mobeendev sure, you can take it. All the info about installation and config is [in the Wiki](https://github.com/eduayme/RescueApp/
  
thanks man, configured following wiki and working :)

**Comment by mobeendev** [comment]
@eduayme hey I understood this thing from above illustration:
![image](https://user-images.githubusercontent.com/10846423/70865492-6421f780-1f6f-11ea-8375-000cbf601d73.png)
Can you please check and tell me so that I can go ahead.
Thanks in advance :)

**Comment by eduayme** [comment]
@mobeendev it is not like this. The "Incidents" would be another tab, between "Data" and "Finish". It is another type of incidents, the ones than happens during that search, not the one that happened to the lost person. 

<img width="1440" alt="Screenshot 2019-12-15 at 17 21 57" src="https://user-images.githubusercontent.com/26260104/70865677-78122d00-1f60-11ea-90cb-eb6ceed03349.png">
<img width="1440" alt="Screenshot 2019-12-15 at 17 21 57 copy" src="https://user-images.githubusercontent.com/26260104/70865678-78122d00-1f60-11ea-9de2-15cc6dfda8ac.png">

This new tab will contain the new incidents that happen during the search:
<img width="1440" alt="Screenshot 2019-12-15 at 17 21 57 copy" src="https://user-images.githubusercontent.com/26260104/70865852-6df12e00-1f62-11ea-93ca-44ce47e34136.png">

**Comment by mobeendev** [comment]
> @mobeendev it is not like this. The "Incidents" would be another tab, between "Data" and "Finish". It is another type of incidents, the ones than happens during that search, not the one that happened to the lost person.
> 
> <img alt="Screenshot 2019-12-15 at 17 21 57" width="1440" src="https://user-images.githubusercontent.com/26260104/70865677-78122d00-1f60-11ea-90cb-eb6ceed03349.png">
> 
> <img alt="Screenshot 2019-12-15 at 17 21 57 copy" width="1440" src="https://user-images.githubusercontent.com/26260104/70865678-78122d00-1f60-11ea-9de2-15cc6dfda8ac.png">
> 
> This new tab will contain the new incidents that happen during the search:
> <img alt="Screenshot 2019-12-15 at 17 21 57 copy" width="1440" src="https://user-images.githubusercontent.com/26260104/70865852-6df12e00-1f62-11ea-93ca-44ce47e34136.png">

@eduayme thanks, now I got it 👍

**Comment by Dhavalc2012** [comment]
@eduayme Can you post the screenshots from the original post in English? That would be really helpful for me to understand the fields that are in the forms and displayed.

**Comment by eduayme** [comment]
@Dhavalc2012 sure. Here are the initial design. Navbar and tabs changes but all table fields and forms are the same as it should be.

List incidents:
![Recerca - Incidencies – 1](https://user-images.githubusercontent.com/26260104/75286243-798d8a80-5818-11ea-861e-a4f8cd56d1c1.png)

Create incident:
![Recerca - Incidencies – Crear Incidencia – 1](https://user-images.githubusercontent.com/26260104/75286248-7befe480-5818-11ea-8c59-64c0e1d87921.png)

Edit incident:
![Recerca - Incidencies – Editar Incidencia – 1](https://user-images.githubusercontent.com/26260104/75286250-7c887b00-5818-11ea-81a6-0eef9565cb84.png)

Modal display after click on image*:
![Recerca - Incidencies – Foto 1](https://user-images.githubusercontent.com/26260104/75286252-7c887b00-5818-11ea-92a5-103c305d439f.png)

Modal display after click on image*:
![Recerca - Incidencies – Foto 2](https://user-images.githubusercontent.com/26260104/75286255-7db9a800-5818-11ea-8b79-0a36cceead3a.png)

*Incidents can have multiple images so the modal display is a carousel of all this images. To add and edit multiple items probably the only button "Files" should be improved with a dropzone or something similar to make it easier to add, edit or remove more than one image.

**Comment by Dhavalc2012** [comment]
Thanks @eduayme . Any progress on this @mobeendev .

**Comment by Dhavalc2012** [comment]
Hey @eduayme . If no one is working on this task, can you assign this task to me?

**Comment by eduayme** [comment]
@Dhavalc2012 yeah

**Comment by mobeendev** [comment]
@Dhavalc2012,Yeah you can take this, I started but wasn't able to deliver.

**Comment by Dhavalc2012** [comment]
@mobeendev :+1: I am currently working on it now.

**Comment by Dhavalc2012** [comment]
Sorry there was a delay since I had to give my laptop for reparing. Just got it back and working on this feature now.

**Comment by Dhavalc2012** [comment]
To add or remove images, do you want the dropzone in the same popup modal where we add or edit information? Or a separate file button next to the action buttons on listing?

**Comment by eduayme** [comment]
I was thinking about using a dropzone (https://www.dropzonejs.com) in the same popup modal.

**Comment by Dhavalc2012** [comment]
Yeah I reviewed that yesterday. I was thinking if the same modal is a good choice or not since the modal can get very big if there are too many images and the text content.

**Comment by eduayme** [comment]
Yeah you are right. A new window it is okay then, this was just the first mockup and can be changed and improved. Thanks for the ideas @Dhavalc2012! :)

**Comment by Dhavalc2012** [comment]
@eduayme Currently I built a bootstrap modal and I was trying to integrate the daterangepicker. But daterangepicker has an issue with selecting the timing in the modal on firefox but works on chrome. Should I try to integrate some other date and time picker? Also, on submit should be performed ajax request or the complete page load? I couldn't find any reactive api on the web application so I thought it is better to clear it out.

**Comment by eduayme** [comment]
@Dhavalc2012 Yes, if that time picker is broken then another is fine.
Regarding the submit I didn't think about that. I think an ajax request would be better but if it works with complete page load it is also okey.
