### ISSUE TITLE
[FEATURE] Allow users to have multiple permissions

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#54]
**Is your feature request related to a problem? Please describe.**
Allow users to have multiple permissions

**Describe the solution you'd like**
Implement in the BD a N to N relationship

**Comment by eniabiola** [comment]
Hope you don't mind assigning this task to me.  I shall work on figuring out this feature implementation.

**Comment by eduayme** [comment]
Sure @eniabiola

**Comment by eniabiola** [comment]
I am using **Laratrust** package to add permissions and roles, so users can be given certain permissions based on their roles, and custom permissions.
