### ISSUE TITLE
[BUG] Fix docs

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#66]
**Describe the bug**
Docs page not displaying.

**To Reproduce**
1. Click on 'Documentation' at the footer
2. See error 404 not found

**Expected behavior**
See the LaRecipe documentation style. https://larecipe.binarytorch.com.my/docs/2.2/installation

**Comment by saksham93** [comment]
Can I pick this issue?

**Comment by eduayme** [comment]
@saksham93 Sure
