### ISSUE TITLE
[BUG] Wrong error during registration. 

### ISSUE THREAD

**Issue by Dhavalc2012** [eduayme/RescueApp#70]
While registration, ID field throws an error of " This field must contain less than 50 characters. which is quite confusing. Instead " This field only accepts characters. " seems more appropriate. 

Steps to reproduce.
1. Goto register page.
2, For id field, fill in input such as "ABCDEFGHIJ1122334455"
3. Fill in the rest of the details.
4. Click on the register button.

![image](https://user-images.githubusercontent.com/7031028/73940730-f4087000-4926-11ea-85a7-e3b0d3cd1df3.png)

 - OS: Lubuntu
 - Browser Firefox
 - Version 72.0.2

**Comment by eduayme** [comment]
Hi @Dhavalc2012! Yes, the error message should display "This field must contain less than 10 characters". The ID in Spain have between 8 and 10 with letters and numbers. A correct ID would be: 12345678A. The limits are min 8 and max 10. I will fix this. Thanks! :)

**Comment by Dhavalc2012** [comment]
Oh. So, in that case, wouldn't it be better if you put the message "Lenght of ID should be between 8 and 10" rather than "This field must contain less than 10 characters"

**Comment by eduayme** [comment]
Yes, this message would make much more sense. Thanks for the feedback.

**Comment by eduayme** [comment]
Solved in the commit [9c61c9f8221237219d4d70890bc58087dc8935d0](https://github.com/eduayme/RescueApp/commit/9c61c9f8221237219d4d70890bc58087dc8935d0)

![FireShot Capture 079 - Register - Aplicatiu de Recerques - localhost](https://user-images.githubusercontent.com/26260104/73958241-eabbdb00-4907-11ea-91aa-f7ebb92f06ba.png)
