### ISSUE TITLE
[FEATURE] Adding Breadcrumb

### ISSUE THREAD

**Issue by Dhavalc2012** [eduayme/RescueApp#74]
Description of the problem :
Currently, there seems to be no way to go back to the dashboard table after filling up the details for the new search and saving it. 

Breadcrumb similar to this (https://getbootstrap.com/docs/3.3/components/#breadcrumbs) will improve the navigation of the web app and help the users in productivity. 

![image](https://user-images.githubusercontent.com/7031028/73960693-502ebc80-4946-11ea-8309-d956fa60eee3.png)

**Comment by ragontan** [comment]
I am still new to this. But hope this helps:
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{URL::to('/')}}">Dashboard</a></li>
    <li class="breadcrumb-item">{{Route::current()->getName()}}</li>
</ol>

**Comment by ragontan** [comment]
I am still new to this, but hope this helps.
`<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{URL::to('/')}}">Dashboard</a></li>
    <li class="breadcrumb-item">{{Route::current()->getName()}}</li>
</ol>`

**Comment by khoa002** [comment]
Hello. I've set up the project locally but have no local data to work with. I've migrated but it seems there were no seeds for sample data. Would it be possible to get some sample data so I can traverse through the pages to plan out how to add this feature?

Thanks,

![image](https://user-images.githubusercontent.com/4231450/75474763-ceceb680-5954-11ea-8ad6-7a0800e4288b.png)

**Comment by eduayme** [comment]
@khoa002 when you start the project from scratch by default there are 2 users. The first one is the admin, who can create, edit and delete everything. The second one is the guest who can only view the data. You can log in with the user admin to add information yourself. 

Email: admin@gmail.com
Password: admin

**Comment by khoa002** [comment]
@eduayme Thank you. Next question would be if there's a project board that outlines somewhat what you're looking for? Just want to make sure I don't get started and miss the acceptance criteria completely (if any).

**Comment by eduayme** [comment]
@khoa002 There is no project board yet to see what I am looking for. I am working on it. I wasn't thinking about adding a Breadcrumb but I guess the number of pages are growing so it is not a bad idea to have it. Just try to follow the same style and add the component on top of pages.
