### ISSUE TITLE
[BUG] Extra Spaces in the text fields.

### ISSUE THREAD

**Issue by Dhavalc2012** [eduayme/RescueApp#75]
There are extra spaces in the text field of the Add Search form (on create route). Removing them will be a minor improvement for the user experience.

![image](https://user-images.githubusercontent.com/7031028/74035904-29c85a00-49f6-11ea-81ab-782ed70daaf7.png)

 - OS: LUbuntu 18.04
 - Browser Firefox 
 - Version 72.0.

**Comment by Dhavalc2012** [comment]
Can you assign me to this task ? Will be helpful for me to start contributing with solving a minor bug 😅

**Comment by eduayme** [comment]
@Dhavalc2012 sure, of course.
