### ISSUE TITLE
Add admin page

### ISSUE THREAD

**Issue by eduayme** [eduayme/RescueApp#8]
Add a page just for admin type of users.
The page will allow users to:

- [ ] See all current users.
- [ ] Modify or delete all users that are not admins.
- [ ] See a log of activities from all users.

**Comment by Sweta271097** [comment]
@eduayme Do we just have work on the front-end for this issue?

**Comment by eduayme** [comment]
> @eduayme Do we just have work on the front-end for this issue?

@Sweta271097 No. This issue has work for the frontend and backend. 

- In the backend:
- [ ] The API needs to have a function to get all users.
- [ ] A controller to be able to modify and delete info from users (only allowed for admin users).
- [ ] Modify the database to save all the users activity.
- [ ] The API call to get all this activity. 

- In the frontend:
- [ ] An extra page with 2 tabs: one to display all users (actions modify and delete next to each user name that is not an admin).
- [ ] Display all logs from users (recent activity first at the top).
- [ ] Add a link in the navbar only displayed for admins users.
