### ISSUE TITLE
[BUG] Can't add search with search id of 2 characters

### ISSUE THREAD

**Issue by gyaaniguy** [eduayme/RescueApp#97]
**Describe the bug**
Getting message of Search ID being too small, when its not

**To Reproduce**
Go at "add search" . 
Enter search ID having 2 characters
Submit.
Get error complaining about search id not being 2 char long.

**Screenshots**

![image](https://user-images.githubusercontent.com/929990/80945045-8a561000-8e08-11ea-9440-95c08267df16.png)

**Issue** 
The validation of field "id_search" is set as 'min:3' . Should this be min:2 ? Or should the message be changed? 
I would like to send a PR.

**Comment by eduayme** [comment]
The min:3 should be changed for min:2

**Comment by eduayme** [comment]
Fixed in a new commit [c7fc6fb](https://github.com/eduayme/RescueApp/commit/c7fc6fbd4f2c7b8d7baa10f9d0afce7ece483b29)
